/**
 * Additional AI coding assets: Roles, Skills, Hooks, Workflows.
 * Merged into RULES_DATA by rules.js.
 */
window.EXTRA_ASSETS = [
  {
    id: 'senior-fullstack-developer-role',
    title: 'Senior Full-Stack Developer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Full-Stack',
    framework: 'Generic',
    description: 'A senior engineering role prompt for building production-ready full-stack features with clear planning, clean architecture, and safe implementation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Full-Stack', 'Architecture', 'Production'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['New feature development', 'Production-ready implementation', 'Architecture planning'],
    relatedItems: ['nextjs-architect-role', 'build-production-ready-feature-hook'],
    content: 'Act as a senior full-stack developer. Before writing code, inspect the current project structure, identify the relevant files, explain the implementation plan, and highlight risks. Then implement the feature step by step using clean, maintainable, production-ready code. Avoid unnecessary rewrites. Preserve existing behavior unless explicitly asked to change it.'
  },
  {
    id: 'nextjs-architect-role',
    title: 'Next.js Architect Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Full-Stack',
    framework: 'Next.js',
    description: 'A Next.js architecture role for App Router, server components, API routes, and production-ready structure.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Next.js', 'App Router', 'Architecture'],
    difficulty: 'Advanced',
    popularity: 'high',
    useCases: ['Next.js project setup', 'App Router refactoring', 'Server/client boundaries'],
    relatedItems: ['nextjs-fullstack', 'nextjs-app-router', 'optimize-performance-skill'],
    content: 'Act as a senior Next.js architect. Review the current App Router structure, component boundaries, server/client component usage, data fetching, API routes, metadata, and performance risks. Propose a clean implementation plan before editing. Prefer simple, scalable patterns and avoid unnecessary abstractions.'
  },
  {
    id: 'react-frontend-engineer-role',
    title: 'React Frontend Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Frontend',
    framework: 'React',
    description: 'A frontend role for building clean, reusable, accessible React UI.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'React', 'UI', 'Accessibility'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Component development', 'UI refactoring', 'Accessible markup'],
    relatedItems: ['react-frontend', 'react-typescript-components', 'improve-ui-polish-skill'],
    content: 'Act as a senior React frontend engineer. Build reusable components with clear props, accessible markup, predictable state management, and clean styling. Keep components small and maintainable. Avoid duplicating UI logic. Explain important trade-offs before making large changes.'
  },
  {
    id: 'typescript-expert-role',
    title: 'TypeScript Expert Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Frontend',
    framework: 'TypeScript',
    description: 'A TypeScript role for safer types, better interfaces, and fewer runtime errors.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'TypeScript', 'Type Safety'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Type improvements', 'Interface design', 'Removing unsafe any'],
    relatedItems: ['typescript-general', 'react-typescript-components'],
    content: 'Act as a TypeScript expert. Improve type safety without overengineering. Replace unsafe any types where practical, define clear interfaces, use discriminated unions when helpful, and make errors easier to catch at compile time. Preserve runtime behavior unless asked otherwise.'
  },
  {
    id: 'ai-code-reviewer-role',
    title: 'AI Code Reviewer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Testing',
    framework: 'Generic',
    description: 'A code review role for finding bugs, maintainability issues, security risks, and edge cases.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Code Review', 'Quality', 'Security'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Pull request review', 'Pre-merge quality checks', 'Security audit'],
    relatedItems: ['ai-code-review-security', 'review-pull-request-skill', 'review-like-senior-engineer-hook'],
    content: 'Act as a senior code reviewer. Review this code for bugs, security risks, edge cases, performance problems, poor abstractions, duplicated logic, missing tests, and maintainability issues. Prioritize the most important findings first. Suggest concrete fixes with minimal unnecessary changes.'
  },
  {
    id: 'debugging-expert-role',
    title: 'Debugging Expert Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Debugging',
    framework: 'Generic',
    description: 'A debugging role that focuses on root cause analysis before changing code.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Debugging', 'Root Cause'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['Bug investigation', 'Production issues', 'Regression analysis'],
    relatedItems: ['fix-bugs-step-by-step-skill', 'find-root-cause-hook'],
    content: 'Act as a debugging expert. Do not guess. First identify the expected behavior, actual behavior, relevant files, likely root causes, and the smallest test or reproduction that can confirm the issue. Only then propose and implement the safest fix.'
  },
  {
    id: 'security-engineer-role',
    title: 'Security Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Security',
    framework: 'Generic',
    description: 'A security role for authentication, authorization, validation, secrets, and data exposure.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Security', 'Auth', 'Validation'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Security audit', 'Auth flow review', 'Input validation'],
    relatedItems: ['ai-code-review-security', 'secure-authentication-skill', 'audit-security-hook'],
    content: 'Act as a security engineer. Audit this code for authentication, authorization, input validation, secret exposure, unsafe API access, data leaks, insecure dependencies, and missing error handling. Prioritize practical fixes and avoid breaking the user experience.'
  },
  {
    id: 'saas-product-engineer-role',
    title: 'SaaS Product Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'SaaS',
    framework: 'Next.js',
    description: 'A product-focused engineering role for building SaaS MVP features quickly and safely.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'SaaS', 'MVP', 'Product'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['SaaS feature shipping', 'MVP development', 'Billing readiness'],
    relatedItems: ['build-saas-mvp-skill', 'saas-product-engineer-role'],
    content: 'Act as a SaaS product engineer. Focus on shipping a simple, useful, production-ready feature. Prioritize user flow, clear UI states, authentication boundaries, data model correctness, billing readiness, and maintainable implementation. Avoid unnecessary complexity.'
  },
  {
    id: 'devops-deployment-expert-role',
    title: 'DevOps Deployment Expert Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'DevOps',
    framework: 'Generic',
    description: 'A DevOps role for preparing projects for deployment.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'DevOps', 'Deployment', 'CI/CD'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Production deployment', 'Build configuration', 'Environment setup'],
    relatedItems: ['docker-devops', 'github-actions-ci', 'prepare-for-deployment-hook'],
    content: 'Act as a DevOps deployment expert. Inspect the project setup, build scripts, environment variables, deployment target, routing, static assets, and production risks. Prepare the project for a clean deployment with clear steps and minimal configuration errors.'
  },
  {
    id: 'test-automation-engineer-role',
    title: 'Test Automation Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Testing',
    framework: 'Playwright',
    description: 'A testing role for unit tests, integration tests, and E2E coverage.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Testing', 'Playwright', 'Automation'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Test strategy', 'E2E coverage', 'CI test setup'],
    relatedItems: ['playwright-e2e', 'vitest-unit', 'add-playwright-e2e-tests-skill'],
    content: 'Act as a test automation engineer. Identify the most important user flows and risky logic first. Add practical tests that catch real regressions. Prefer readable tests over excessive coverage. Explain how to run the tests after implementation.'
  },
  {
    id: 'build-saas-mvp-skill',
    title: 'Build SaaS MVP Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'SaaS',
    framework: 'Next.js',
    description: 'Build a simple SaaS MVP with authentication, dashboard, database, and clean structure.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'SaaS', 'MVP', 'Next.js'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['Greenfield SaaS', 'MVP scaffolding', 'Auth + dashboard setup'],
    relatedItems: ['saas-product-engineer-role', 'supabase-auth-rls'],
    content: 'Help me build a SaaS MVP. First inspect the project, then propose a minimal feature scope, folder structure, data model, pages, components, and implementation steps. Prioritize speed, clarity, and production readiness.'
  },
  {
    id: 'fix-bugs-step-by-step-skill',
    title: 'Fix Bugs Step-by-Step Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Debugging',
    framework: 'Generic',
    description: 'Debug a problem systematically instead of making random changes.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Debugging', 'Bug Fix'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Bug fixing', 'Regression debugging', 'Error investigation'],
    relatedItems: ['debugging-expert-role', 'find-root-cause-hook'],
    content: 'Fix this bug step by step. First summarize the bug, identify likely causes, inspect the relevant files, create a minimal hypothesis, and explain the safest fix. Do not change unrelated files.'
  },
  {
    id: 'review-pull-request-skill',
    title: 'Review Pull Request Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Testing',
    framework: 'Generic',
    description: 'Review a PR like a senior engineer.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Code Review', 'PR'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['PR review', 'Pre-merge checks', 'Team feedback'],
    relatedItems: ['ai-code-reviewer-role', 'review-like-senior-engineer-hook'],
    content: 'Review this pull request for correctness, edge cases, security, performance, readability, maintainability, and missing tests. Group feedback by severity: critical, important, minor, and optional.'
  },
  {
    id: 'refactor-legacy-code-skill',
    title: 'Refactor Legacy Code Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Refactoring',
    framework: 'Generic',
    description: 'Refactor old code safely without changing behavior.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Refactoring', 'Legacy Code'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Legacy cleanup', 'Safe refactoring', 'Technical debt'],
    relatedItems: ['refactor-without-breaking-hook'],
    content: 'Refactor this legacy code without changing behavior. First identify responsibilities, duplicated logic, hidden dependencies, and risky areas. Then refactor in small safe steps. Preserve public APIs unless a change is explicitly required.'
  },
  {
    id: 'generate-unit-tests-skill',
    title: 'Generate Unit Tests Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Testing',
    framework: 'Vitest',
    description: 'Generate useful unit tests for important business logic.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Testing', 'Vitest', 'Unit Tests'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Unit test coverage', 'Business logic testing', 'Regression prevention'],
    relatedItems: ['vitest-unit', 'add-tests-for-risky-code-hook'],
    content: 'Generate unit tests for the most important logic in this file. Cover normal cases, edge cases, invalid inputs, and regression risks. Keep tests readable and explain how to run them.'
  },
  {
    id: 'add-playwright-e2e-tests-skill',
    title: 'Add Playwright E2E Tests Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Testing',
    framework: 'Playwright',
    description: 'Add browser tests for core user journeys.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Playwright', 'E2E', 'Testing'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['E2E test setup', 'User journey testing', 'CI browser tests'],
    relatedItems: ['playwright-e2e', 'test-automation-engineer-role'],
    content: 'Add Playwright E2E tests for the core user flow. Identify the most important journey, create stable selectors if needed, avoid brittle waits, and explain how to run the tests locally and in CI.'
  },
  {
    id: 'improve-ui-polish-skill',
    title: 'Improve UI Polish Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Frontend',
    framework: 'Tailwind CSS',
    description: 'Improve the interface so it looks like a modern SaaS product.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'UI', 'Tailwind CSS', 'Design'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['UI polish', 'SaaS styling', 'Responsive design'],
    relatedItems: ['tailwind-ui', 'improve-ui-like-saas-hook'],
    content: 'Polish this UI to look like a modern SaaS product. Improve spacing, hierarchy, typography, responsiveness, empty states, button states, hover states, and visual consistency. Do not change the core functionality.'
  },
  {
    id: 'optimize-performance-skill',
    title: 'Optimize Performance Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Performance',
    framework: 'Next.js',
    description: 'Improve frontend or full-stack performance safely.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Performance', 'Next.js', 'Optimization'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Bundle optimization', 'Rendering performance', 'Data fetching tuning'],
    relatedItems: ['nextjs-fullstack', 'nextjs-architect-role'],
    content: 'Optimize this project for performance. Inspect bundle size, rendering behavior, data fetching, caching, image usage, unnecessary re-renders, and slow API calls. Recommend the highest-impact changes first.'
  },
  {
    id: 'secure-authentication-skill',
    title: 'Secure Authentication Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Security',
    framework: 'Generic',
    description: 'Review and improve authentication and authorization logic.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Security', 'Auth', 'Authorization'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Auth hardening', 'Session security', 'Route protection'],
    relatedItems: ['authjs-nextauth', 'supabase-auth-rls', 'audit-security-hook'],
    content: 'Review the authentication and authorization flow. Check route protection, session handling, API access control, role permissions, token handling, redirects, and user data exposure. Suggest safe improvements.'
  },
  {
    id: 'write-readme-docs-skill',
    title: 'Write README and Docs Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Documentation',
    framework: 'Generic',
    description: 'Generate clear project documentation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Documentation', 'README'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['README creation', 'Onboarding docs', 'Setup instructions'],
    relatedItems: ['explain-codebase-hook'],
    content: 'Create or improve the README for this project. Include what the project does, tech stack, setup steps, environment variables, available scripts, folder structure, deployment notes, and common troubleshooting tips.'
  },
  {
    id: 'plan-before-coding-hook',
    title: 'Plan Before Coding Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Full-Stack',
    framework: 'Generic',
    description: 'A short hook that forces planning before implementation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Planning', 'Implementation'],
    difficulty: 'Beginner',
    popularity: 'high',
    useCases: ['Start of any coding task', 'Feature planning', 'Risk assessment'],
    relatedItems: ['senior-fullstack-developer-role', 'build-production-ready-feature-hook'],
    content: 'Before coding, inspect the project and give me a step-by-step implementation plan.'
  },
  {
    id: 'find-root-cause-hook',
    title: 'Find Root Cause Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Debugging',
    framework: 'Generic',
    description: 'A debugging hook that prevents random code changes.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Debugging', 'Root Cause'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Bug fixing', 'Error investigation'],
    relatedItems: ['debugging-expert-role', 'fix-bugs-step-by-step-skill'],
    content: 'Find the root cause before changing any code.'
  },
  {
    id: 'refactor-without-breaking-hook',
    title: 'Refactor Without Breaking Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Refactoring',
    framework: 'Generic',
    description: 'A safe refactoring hook.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Refactoring', 'Safe Changes'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Legacy refactoring', 'Code cleanup'],
    relatedItems: ['refactor-legacy-code-skill'],
    content: 'Refactor this without changing behavior.'
  },
  {
    id: 'review-like-senior-engineer-hook',
    title: 'Review Like Senior Engineer Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Testing',
    framework: 'Generic',
    description: 'A code review hook.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Code Review'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Quick code review', 'PR feedback'],
    relatedItems: ['ai-code-reviewer-role', 'review-pull-request-skill'],
    content: 'Review this like a senior engineer and prioritize the most important issues first.'
  },
  {
    id: 'build-production-ready-feature-hook',
    title: 'Build Production-Ready Feature Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Full-Stack',
    framework: 'Generic',
    description: 'A hook for feature development.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Feature Development', 'Production'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Feature implementation', 'Production quality'],
    relatedItems: ['senior-fullstack-developer-role', 'plan-before-coding-hook'],
    content: 'Build this feature in a production-ready way with clean structure, error states, and maintainable code.'
  },
  {
    id: 'add-tests-for-risky-code-hook',
    title: 'Add Tests for Risky Code Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Testing',
    framework: 'Generic',
    description: 'A hook for practical testing.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Testing', 'Risk'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Targeted test coverage', 'Risk-based testing'],
    relatedItems: ['generate-unit-tests-skill', 'add-playwright-e2e-tests-skill'],
    content: 'Add tests for the riskiest parts of this code first.'
  },
  {
    id: 'explain-codebase-hook',
    title: 'Explain Codebase Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Documentation',
    framework: 'Generic',
    description: 'A hook for understanding a new project.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Documentation', 'Onboarding'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['New team onboarding', 'Project exploration'],
    relatedItems: ['write-readme-docs-skill'],
    content: 'Explain this codebase like I am joining the team tomorrow.'
  },
  {
    id: 'improve-ui-like-saas-hook',
    title: 'Improve UI Like SaaS Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Frontend',
    framework: 'Tailwind CSS',
    description: 'A hook for UI polish.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'UI', 'SaaS', 'Tailwind CSS'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['UI quick polish', 'SaaS styling'],
    relatedItems: ['improve-ui-polish-skill', 'tailwind-ui'],
    content: 'Improve this UI so it feels like a polished modern SaaS product.'
  },
  {
    id: 'audit-security-hook',
    title: 'Audit Security Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Security',
    framework: 'Generic',
    description: 'A hook for security review.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Security', 'Audit'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Security quick check', 'Auth audit'],
    relatedItems: ['security-engineer-role', 'secure-authentication-skill'],
    content: 'Audit this code for auth issues, input validation problems, data leaks, and unsafe API access.'
  },
  {
    id: 'prepare-for-deployment-hook',
    title: 'Prepare for Deployment Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'DevOps',
    framework: 'Generic',
    description: 'A hook for production readiness.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'DevOps', 'Deployment'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Pre-deploy checklist', 'Build verification'],
    relatedItems: ['devops-deployment-expert-role', 'docker-devops'],
    content: 'Prepare this project for production deployment and list anything that could fail during build or deploy.'
  },
  {
    id: 'mcp-server-setup-workflow',
    title: 'MCP Server Setup Workflow',
    tool: 'MCP',
    assetType: 'Workflows',
    category: 'AI Agent',
    framework: 'Generic',
    description: 'Step-by-step workflow for setting up a Model Context Protocol server and connecting it to AI coding agents.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Workflow', 'MCP', 'AI Agent', 'Integration'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['MCP server setup', 'Tool integration', 'Agent configuration'],
    relatedItems: ['mcp-server'],
    content: '# MCP Server Setup Workflow\n\nFollow these steps to set up an MCP server for AI coding agents:\n\n1. **Define tools** — List the capabilities your MCP server will expose (search, fetch, execute).\n2. **Scaffold the server** — Use the MCP SDK for TypeScript or Python with typed tool schemas.\n3. **Implement handlers** — Write safe, validated handlers for each tool with clear error messages.\n4. **Configure transport** — Choose stdio for local editors or SSE/HTTP for remote access.\n5. **Add to your editor** — Register the server in Cursor MCP settings, Claude Code, or Windsurf MCP config.\n6. **Test end-to-end** — Verify each tool works from the agent chat with realistic inputs.\n7. **Document usage** — Add a README with setup commands, env vars, and example prompts.'
  }
];
