/**
 * Additional AI coding assets: Roles, Skills, Hooks, Workflows.
 * Merged into RULES_DATA by rules.js.
 */
window.EXTRA_ASSETS = [
  {
    id: 'senior-fullstack-developer-role',
    title: 'Senior Full-Stack Developer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Full-Stack',
    framework: 'Generic',
    description: 'A senior engineering role prompt for building production-ready full-stack features with clear planning, clean architecture, and safe implementation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Full-Stack', 'Architecture', 'Production'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['New feature development', 'Production-ready implementation', 'Architecture planning'],
    relatedItems: ['nextjs-architect-role', 'build-production-ready-feature-hook'],
    content: 'Act as a senior full-stack developer. Before writing code, inspect the current project structure, identify the relevant files, explain the implementation plan, and highlight risks. Then implement the feature step by step using clean, maintainable, production-ready code. Avoid unnecessary rewrites. Preserve existing behavior unless explicitly asked to change it.'
  },
  {
    id: 'nextjs-architect-role',
    title: 'Next.js Architect Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Full-Stack',
    framework: 'Next.js',
    description: 'A Next.js architecture role for App Router, server components, API routes, and production-ready structure.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Next.js', 'App Router', 'Architecture'],
    difficulty: 'Advanced',
    popularity: 'high',
    useCases: ['Next.js project setup', 'App Router refactoring', 'Server/client boundaries'],
    relatedItems: ['nextjs-fullstack', 'nextjs-app-router', 'optimize-performance-skill'],
    content: 'Act as a senior Next.js architect. Review the current App Router structure, component boundaries, server/client component usage, data fetching, API routes, metadata, and performance risks. Propose a clean implementation plan before editing. Prefer simple, scalable patterns and avoid unnecessary abstractions.'
  },
  {
    id: 'react-frontend-engineer-role',
    title: 'React Frontend Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Frontend',
    framework: 'React',
    description: 'A frontend role for building clean, reusable, accessible React UI.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'React', 'UI', 'Accessibility'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Component development', 'UI refactoring', 'Accessible markup'],
    relatedItems: ['react-frontend', 'react-typescript-components', 'improve-ui-polish-skill'],
    content: 'Act as a senior React frontend engineer. Build reusable components with clear props, accessible markup, predictable state management, and clean styling. Keep components small and maintainable. Avoid duplicating UI logic. Explain important trade-offs before making large changes.'
  },
  {
    id: 'typescript-expert-role',
    title: 'TypeScript Expert Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Frontend',
    framework: 'TypeScript',
    description: 'A TypeScript role for safer types, better interfaces, and fewer runtime errors.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'TypeScript', 'Type Safety'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Type improvements', 'Interface design', 'Removing unsafe any'],
    relatedItems: ['typescript-general', 'react-typescript-components'],
    content: 'Act as a TypeScript expert. Improve type safety without overengineering. Replace unsafe any types where practical, define clear interfaces, use discriminated unions when helpful, and make errors easier to catch at compile time. Preserve runtime behavior unless asked otherwise.'
  },
  {
    id: 'ai-code-reviewer-role',
    title: 'AI Code Reviewer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Testing',
    framework: 'Generic',
    description: 'A code review role for finding bugs, maintainability issues, security risks, and edge cases.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Code Review', 'Quality', 'Security'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Pull request review', 'Pre-merge quality checks', 'Security audit'],
    relatedItems: ['ai-code-review-security', 'review-pull-request-skill', 'review-like-senior-engineer-hook'],
    content: 'Act as a senior code reviewer. Review this code for bugs, security risks, edge cases, performance problems, poor abstractions, duplicated logic, missing tests, and maintainability issues. Prioritize the most important findings first. Suggest concrete fixes with minimal unnecessary changes.'
  },
  {
    id: 'debugging-expert-role',
    title: 'Debugging Expert Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Debugging',
    framework: 'Generic',
    description: 'A debugging role that focuses on root cause analysis before changing code.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Debugging', 'Root Cause'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['Bug investigation', 'Production issues', 'Regression analysis'],
    relatedItems: ['fix-bugs-step-by-step-skill', 'find-root-cause-hook'],
    content: 'Act as a debugging expert. Do not guess. First identify the expected behavior, actual behavior, relevant files, likely root causes, and the smallest test or reproduction that can confirm the issue. Only then propose and implement the safest fix.'
  },
  {
    id: 'security-engineer-role',
    title: 'Security Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Security',
    framework: 'Generic',
    description: 'A security role for authentication, authorization, validation, secrets, and data exposure.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Security', 'Auth', 'Validation'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Security audit', 'Auth flow review', 'Input validation'],
    relatedItems: ['ai-code-review-security', 'secure-authentication-skill', 'audit-security-hook'],
    content: 'Act as a security engineer. Audit this code for authentication, authorization, input validation, secret exposure, unsafe API access, data leaks, insecure dependencies, and missing error handling. Prioritize practical fixes and avoid breaking the user experience.'
  },
  {
    id: 'saas-product-engineer-role',
    title: 'SaaS Product Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'SaaS',
    framework: 'Next.js',
    description: 'A product-focused engineering role for building SaaS MVP features quickly and safely.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'SaaS', 'MVP', 'Product'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['SaaS feature shipping', 'MVP development', 'Billing readiness'],
    relatedItems: ['build-saas-mvp-skill', 'saas-product-engineer-role'],
    content: 'Act as a SaaS product engineer. Focus on shipping a simple, useful, production-ready feature. Prioritize user flow, clear UI states, authentication boundaries, data model correctness, billing readiness, and maintainable implementation. Avoid unnecessary complexity.'
  },
  {
    id: 'devops-deployment-expert-role',
    title: 'DevOps Deployment Expert Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'DevOps',
    framework: 'Generic',
    description: 'A DevOps role for preparing projects for deployment.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'DevOps', 'Deployment', 'CI/CD'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Production deployment', 'Build configuration', 'Environment setup'],
    relatedItems: ['docker-devops', 'github-actions-ci', 'prepare-for-deployment-hook'],
    content: 'Act as a DevOps deployment expert. Inspect the project setup, build scripts, environment variables, deployment target, routing, static assets, and production risks. Prepare the project for a clean deployment with clear steps and minimal configuration errors.'
  },
  {
    id: 'test-automation-engineer-role',
    title: 'Test Automation Engineer Role',
    tool: 'Cursor',
    assetType: 'Roles',
    category: 'Testing',
    framework: 'Playwright',
    description: 'A testing role for unit tests, integration tests, and E2E coverage.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Role', 'Testing', 'Playwright', 'Automation'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Test strategy', 'E2E coverage', 'CI test setup'],
    relatedItems: ['playwright-e2e', 'vitest-unit', 'add-playwright-e2e-tests-skill'],
    content: 'Act as a test automation engineer. Identify the most important user flows and risky logic first. Add practical tests that catch real regressions. Prefer readable tests over excessive coverage. Explain how to run the tests after implementation.'
  },
  {
    id: 'build-saas-mvp-skill',
    title: 'Build SaaS MVP Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'SaaS',
    framework: 'Next.js',
    description: 'Build a simple SaaS MVP with authentication, dashboard, database, and clean structure.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'SaaS', 'MVP', 'Next.js'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['Greenfield SaaS', 'MVP scaffolding', 'Auth + dashboard setup'],
    relatedItems: ['saas-product-engineer-role', 'supabase-auth-rls'],
    content: 'Help me build a SaaS MVP. First inspect the project, then propose a minimal feature scope, folder structure, data model, pages, components, and implementation steps. Prioritize speed, clarity, and production readiness.'
  },
  {
    id: 'fix-bugs-step-by-step-skill',
    title: 'Fix Bugs Step-by-Step Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Debugging',
    framework: 'Generic',
    description: 'Debug a problem systematically instead of making random changes.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Debugging', 'Bug Fix'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Bug fixing', 'Regression debugging', 'Error investigation'],
    relatedItems: ['debugging-expert-role', 'find-root-cause-hook'],
    content: 'Fix this bug step by step. First summarize the bug, identify likely causes, inspect the relevant files, create a minimal hypothesis, and explain the safest fix. Do not change unrelated files.'
  },
  {
    id: 'review-pull-request-skill',
    title: 'Review Pull Request Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Testing',
    framework: 'Generic',
    description: 'Review a PR like a senior engineer.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Code Review', 'PR'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['PR review', 'Pre-merge checks', 'Team feedback'],
    relatedItems: ['ai-code-reviewer-role', 'review-like-senior-engineer-hook'],
    content: 'Review this pull request for correctness, edge cases, security, performance, readability, maintainability, and missing tests. Group feedback by severity: critical, important, minor, and optional.'
  },
  {
    id: 'refactor-legacy-code-skill',
    title: 'Refactor Legacy Code Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Refactoring',
    framework: 'Generic',
    description: 'Refactor old code safely without changing behavior.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Refactoring', 'Legacy Code'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Legacy cleanup', 'Safe refactoring', 'Technical debt'],
    relatedItems: ['refactor-without-breaking-hook'],
    content: 'Refactor this legacy code without changing behavior. First identify responsibilities, duplicated logic, hidden dependencies, and risky areas. Then refactor in small safe steps. Preserve public APIs unless a change is explicitly required.'
  },
  {
    id: 'generate-unit-tests-skill',
    title: 'Generate Unit Tests Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Testing',
    framework: 'Vitest',
    description: 'Generate useful unit tests for important business logic.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Testing', 'Vitest', 'Unit Tests'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Unit test coverage', 'Business logic testing', 'Regression prevention'],
    relatedItems: ['vitest-unit', 'add-tests-for-risky-code-hook'],
    content: 'Generate unit tests for the most important logic in this file. Cover normal cases, edge cases, invalid inputs, and regression risks. Keep tests readable and explain how to run them.'
  },
  {
    id: 'add-playwright-e2e-tests-skill',
    title: 'Add Playwright E2E Tests Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Testing',
    framework: 'Playwright',
    description: 'Add browser tests for core user journeys.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Playwright', 'E2E', 'Testing'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['E2E test setup', 'User journey testing', 'CI browser tests'],
    relatedItems: ['playwright-e2e', 'test-automation-engineer-role'],
    content: 'Add Playwright E2E tests for the core user flow. Identify the most important journey, create stable selectors if needed, avoid brittle waits, and explain how to run the tests locally and in CI.'
  },
  {
    id: 'improve-ui-polish-skill',
    title: 'Improve UI Polish Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Frontend',
    framework: 'Tailwind CSS',
    description: 'Improve the interface so it looks like a modern SaaS product.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'UI', 'Tailwind CSS', 'Design'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['UI polish', 'SaaS styling', 'Responsive design'],
    relatedItems: ['tailwind-ui', 'improve-ui-like-saas-hook'],
    content: 'Polish this UI to look like a modern SaaS product. Improve spacing, hierarchy, typography, responsiveness, empty states, button states, hover states, and visual consistency. Do not change the core functionality.'
  },
  {
    id: 'optimize-performance-skill',
    title: 'Optimize Performance Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Performance',
    framework: 'Next.js',
    description: 'Improve frontend or full-stack performance safely.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Performance', 'Next.js', 'Optimization'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Bundle optimization', 'Rendering performance', 'Data fetching tuning'],
    relatedItems: ['nextjs-fullstack', 'nextjs-architect-role'],
    content: 'Optimize this project for performance. Inspect bundle size, rendering behavior, data fetching, caching, image usage, unnecessary re-renders, and slow API calls. Recommend the highest-impact changes first.'
  },
  {
    id: 'secure-authentication-skill',
    title: 'Secure Authentication Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Security',
    framework: 'Generic',
    description: 'Review and improve authentication and authorization logic.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Security', 'Auth', 'Authorization'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: ['Auth hardening', 'Session security', 'Route protection'],
    relatedItems: ['authjs-nextauth', 'supabase-auth-rls', 'audit-security-hook'],
    content: 'Review the authentication and authorization flow. Check route protection, session handling, API access control, role permissions, token handling, redirects, and user data exposure. Suggest safe improvements.'
  },
  {
    id: 'write-readme-docs-skill',
    title: 'Write README and Docs Skill',
    tool: 'Cursor',
    assetType: 'Skills',
    category: 'Documentation',
    framework: 'Generic',
    description: 'Generate clear project documentation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Skill', 'Documentation', 'README'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['README creation', 'Onboarding docs', 'Setup instructions'],
    relatedItems: ['explain-codebase-hook'],
    content: 'Create or improve the README for this project. Include what the project does, tech stack, setup steps, environment variables, available scripts, folder structure, deployment notes, and common troubleshooting tips.'
  },
  {
    id: 'plan-before-coding-hook',
    title: 'Plan Before Coding Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Full-Stack',
    framework: 'Generic',
    description: 'A short hook that forces planning before implementation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Planning', 'Implementation'],
    difficulty: 'Beginner',
    popularity: 'high',
    useCases: ['Start of any coding task', 'Feature planning', 'Risk assessment'],
    relatedItems: ['senior-fullstack-developer-role', 'build-production-ready-feature-hook'],
    content: 'Before coding, inspect the project and give me a step-by-step implementation plan.'
  },
  {
    id: 'find-root-cause-hook',
    title: 'Find Root Cause Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Debugging',
    framework: 'Generic',
    description: 'A debugging hook that prevents random code changes.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Debugging', 'Root Cause'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Bug fixing', 'Error investigation'],
    relatedItems: ['debugging-expert-role', 'fix-bugs-step-by-step-skill'],
    content: 'Find the root cause before changing any code.'
  },
  {
    id: 'refactor-without-breaking-hook',
    title: 'Refactor Without Breaking Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Refactoring',
    framework: 'Generic',
    description: 'A safe refactoring hook.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Refactoring', 'Safe Changes'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Legacy refactoring', 'Code cleanup'],
    relatedItems: ['refactor-legacy-code-skill'],
    content: 'Refactor this without changing behavior.'
  },
  {
    id: 'review-like-senior-engineer-hook',
    title: 'Review Like Senior Engineer Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Testing',
    framework: 'Generic',
    description: 'A code review hook.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Code Review'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Quick code review', 'PR feedback'],
    relatedItems: ['ai-code-reviewer-role', 'review-pull-request-skill'],
    content: 'Review this like a senior engineer and prioritize the most important issues first.'
  },
  {
    id: 'build-production-ready-feature-hook',
    title: 'Build Production-Ready Feature Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Full-Stack',
    framework: 'Generic',
    description: 'A hook for feature development.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Feature Development', 'Production'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Feature implementation', 'Production quality'],
    relatedItems: ['senior-fullstack-developer-role', 'plan-before-coding-hook'],
    content: 'Build this feature in a production-ready way with clean structure, error states, and maintainable code.'
  },
  {
    id: 'add-tests-for-risky-code-hook',
    title: 'Add Tests for Risky Code Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Testing',
    framework: 'Generic',
    description: 'A hook for practical testing.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Testing', 'Risk'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Targeted test coverage', 'Risk-based testing'],
    relatedItems: ['generate-unit-tests-skill', 'add-playwright-e2e-tests-skill'],
    content: 'Add tests for the riskiest parts of this code first.'
  },
  {
    id: 'explain-codebase-hook',
    title: 'Explain Codebase Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Documentation',
    framework: 'Generic',
    description: 'A hook for understanding a new project.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Documentation', 'Onboarding'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['New team onboarding', 'Project exploration'],
    relatedItems: ['write-readme-docs-skill'],
    content: 'Explain this codebase like I am joining the team tomorrow.'
  },
  {
    id: 'improve-ui-like-saas-hook',
    title: 'Improve UI Like SaaS Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Frontend',
    framework: 'Tailwind CSS',
    description: 'A hook for UI polish.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'UI', 'SaaS', 'Tailwind CSS'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['UI quick polish', 'SaaS styling'],
    relatedItems: ['improve-ui-polish-skill', 'tailwind-ui'],
    content: 'Improve this UI so it feels like a polished modern SaaS product.'
  },
  {
    id: 'audit-security-hook',
    title: 'Audit Security Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'Security',
    framework: 'Generic',
    description: 'A hook for security review.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'Security', 'Audit'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Security quick check', 'Auth audit'],
    relatedItems: ['security-engineer-role', 'secure-authentication-skill'],
    content: 'Audit this code for auth issues, input validation problems, data leaks, and unsafe API access.'
  },
  {
    id: 'prepare-for-deployment-hook',
    title: 'Prepare for Deployment Hook',
    tool: 'Cursor',
    assetType: 'Hooks',
    category: 'DevOps',
    framework: 'Generic',
    description: 'A hook for production readiness.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Hook', 'DevOps', 'Deployment'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Pre-deploy checklist', 'Build verification'],
    relatedItems: ['devops-deployment-expert-role', 'docker-devops'],
    content: 'Prepare this project for production deployment and list anything that could fail during build or deploy.'
  },
  {
    id: 'mcp-server-setup-workflow',
    title: 'MCP Server Setup Workflow',
    tool: 'MCP',
    assetType: 'Workflows',
    category: 'AI Agent',
    framework: 'Generic',
    description: 'Step-by-step workflow for setting up a Model Context Protocol server and connecting it to AI coding agents.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Workflow', 'MCP', 'AI Agent', 'Integration'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: ['MCP server setup', 'Tool integration', 'Agent configuration'],
    relatedItems: ['mcp-server'],
    content: '# MCP Server Setup Workflow\n\nFollow these steps to set up an MCP server for AI coding agents:\n\n1. **Define tools** — List the capabilities your MCP server will expose (search, fetch, execute).\n2. **Scaffold the server** — Use the MCP SDK for TypeScript or Python with typed tool schemas.\n3. **Implement handlers** — Write safe, validated handlers for each tool with clear error messages.\n4. **Configure transport** — Choose stdio for local editors or SSE/HTTP for remote access.\n5. **Add to your editor** — Register the server in Cursor MCP settings, Claude Code, or Windsurf MCP config.\n6. **Test end-to-end** — Verify each tool works from the agent chat with realistic inputs.\n7. **Document usage** — Add a README with setup commands, env vars, and example prompts.'
  },
  {
    id: 'github-mcp-config',
    title: 'GitHub MCP Config',
    tool: 'MCP',
    assetType: 'MCP Configs',
    category: 'AI Agent',
    categoryKey: 'ai',
    framework: 'GitHub',
    description: 'A practical MCP configuration concept for connecting an AI coding agent to GitHub repositories, issues, pull requests, and code review workflows.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['MCP', 'GitHub', 'AI Agent', 'Code Review', 'Pull Requests', 'Developer Workflow'],
    difficulty: 'Intermediate',
    popularity: 'high',
    useCases: [
      'Read GitHub issues before coding',
      'Review pull requests',
      'Summarize repository context',
      'Connect issue requirements to code changes',
      'Improve AI-assisted development workflows'
    ],
    relatedItems: ['mcp-server-setup-workflow', 'mcp-server'],
    content: 'Use a GitHub MCP server to let your AI coding agent inspect repositories, read issues, review pull requests, understand code context, and assist with development workflows. Use this when you want the agent to work with GitHub context instead of relying only on local files or pasted snippets.'
  },
  {
    id: 'filesystem-mcp-config',
    title: 'Filesystem MCP Config',
    tool: 'MCP',
    assetType: 'MCP Configs',
    category: 'AI Agent',
    categoryKey: 'ai',
    framework: 'Generic',
    description: 'A filesystem MCP setup concept for giving an AI coding agent structured access to local project files.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['MCP', 'Filesystem', 'Local Files', 'AI Agent', 'Project Context', 'Developer Tools'],
    difficulty: 'Beginner',
    popularity: 'high',
    useCases: [
      'Inspect local project files',
      'Understand folder structure',
      'Search codebase context',
      'Plan implementation steps',
      'Avoid changing unrelated files'
    ],
    relatedItems: ['mcp-server-setup-workflow'],
    content: 'Use a filesystem MCP server when your AI coding agent needs structured access to local files and folders. This helps the agent inspect project structure, read relevant files, and make better implementation plans before suggesting code changes.'
  },
  {
    id: 'browser-mcp-config',
    title: 'Browser MCP Config',
    tool: 'MCP',
    assetType: 'MCP Configs',
    category: 'Testing',
    categoryKey: 'testing',
    framework: 'Playwright',
    description: 'A browser MCP setup concept for web inspection, UI testing, debugging, and browser-based workflows.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['MCP', 'Browser', 'Playwright', 'Testing', 'UI Debugging', 'Web Apps'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Test user flows',
      'Inspect rendered UI',
      'Debug frontend issues',
      'Validate form behavior',
      'Check responsive layouts'
    ],
    relatedItems: ['playwright-e2e', 'add-playwright-e2e-tests-skill'],
    content: 'Use a browser MCP server when your AI coding agent needs to inspect pages, interact with a browser, test UI flows, debug frontend issues, or validate user journeys. This is useful for web apps, SaaS dashboards, forms, and visual QA workflows.'
  },
  {
    id: 'database-mcp-config',
    title: 'Database MCP Config',
    tool: 'MCP',
    assetType: 'MCP Configs',
    category: 'Database',
    categoryKey: 'database',
    framework: 'Generic',
    description: 'A database MCP setup concept for helping AI agents understand schemas, queries, migrations, and data relationships.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['MCP', 'Database', 'SQL', 'Schema', 'Backend', 'AI Agent'],
    difficulty: 'Advanced',
    popularity: 'medium',
    useCases: [
      'Inspect database schema',
      'Review SQL queries',
      'Plan migrations',
      'Debug data relationships',
      'Improve backend implementation'
    ],
    relatedItems: ['supabase-db', 'postgresql-db'],
    content: 'Use a database MCP server when your AI coding agent needs to understand schemas, inspect tables, reason about relationships, review queries, or help design migrations. Use with caution and avoid exposing production secrets or sensitive data.'
  },
  {
    id: 'figma-mcp-config',
    title: 'Figma MCP Config',
    tool: 'MCP',
    assetType: 'MCP Configs',
    category: 'Frontend',
    categoryKey: 'frontend',
    framework: 'Figma',
    description: 'A Figma MCP setup concept for connecting design context to frontend implementation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['MCP', 'Figma', 'Design to Code', 'Frontend', 'UI', 'Components'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Convert design to frontend code',
      'Understand component layout',
      'Match spacing and typography',
      'Improve UI consistency',
      'Support design-to-code workflows'
    ],
    relatedItems: ['tailwind-ui', 'improve-ui-polish-skill'],
    content: 'Use a Figma MCP server when your AI coding agent needs design context before building UI. This can help translate layouts, spacing, typography, components, and design intent into frontend code more accurately.'
  },
  {
    id: 'claude-code-refactoring-role',
    title: 'Claude Code Refactoring Role',
    tool: 'Claude Code',
    assetType: 'Roles',
    category: 'Refactoring',
    categoryKey: 'refactoring',
    framework: 'Generic',
    description: 'A Claude Code role for safely refactoring existing projects without changing behavior.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Claude Code', 'Refactoring', 'Clean Code', 'AI Coding', 'Safe Changes'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Legacy code cleanup', 'Safe refactoring', 'Technical debt reduction'],
    relatedItems: ['refactor-legacy-code-skill', 'refactor-without-breaking-hook'],
    content: 'Act as a careful refactoring engineer. First inspect the existing implementation, identify responsibilities, duplicated logic, risky dependencies, and public APIs. Then refactor in small safe steps without changing behavior. Explain the reasoning behind each major change.'
  },
  {
    id: 'claude-code-debugging-hook',
    title: 'Claude Code Debugging Hook',
    tool: 'Claude Code',
    assetType: 'Hooks',
    category: 'Debugging',
    categoryKey: 'debugging',
    framework: 'Generic',
    description: 'A short Claude Code hook for root-cause debugging.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Claude Code', 'Debugging', 'Root Cause', 'AI Coding', 'Bug Fix'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['Bug fixing', 'Root cause analysis', 'Pre-edit debugging'],
    relatedItems: ['debugging-expert-role', 'find-root-cause-hook'],
    content: 'Before editing, identify the root cause, relevant files, and the smallest safe fix.'
  },
  {
    id: 'claude-code-codebase-explanation-skill',
    title: 'Claude Code Codebase Explanation Skill',
    tool: 'Claude Code',
    assetType: 'Skills',
    category: 'Documentation',
    categoryKey: 'documentation',
    framework: 'Generic',
    description: 'A Claude Code skill for understanding a new or unfamiliar codebase.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Claude Code', 'Codebase Explanation', 'Documentation', 'Onboarding', 'AI Coding'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: ['New project onboarding', 'Architecture overview', 'Team handoff'],
    relatedItems: ['explain-codebase-hook', 'write-readme-docs-skill'],
    content: 'Explain this codebase as if I am joining the project tomorrow. Summarize the architecture, key folders, main data flow, important dependencies, risky areas, and the best files to inspect first.'
  },
  {
    id: 'github-copilot-pr-review-prompt',
    title: 'GitHub Copilot PR Review Prompt',
    tool: 'GitHub Copilot',
    assetType: 'Skills',
    category: 'Testing',
    categoryKey: 'testing',
    framework: 'GitHub',
    description: 'A GitHub Copilot prompt for reviewing pull requests clearly and practically.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['GitHub Copilot', 'Pull Request', 'Code Review', 'Testing', 'Developer Workflow'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Pull request review', 'Pre-merge quality checks', 'Team feedback'],
    relatedItems: ['review-pull-request-skill', 'ai-code-reviewer-role'],
    content: 'Review this pull request for correctness, edge cases, security issues, performance risks, readability, maintainability, and missing tests. Group feedback by severity and suggest concrete improvements.'
  },
  {
    id: 'github-copilot-test-generation-prompt',
    title: 'GitHub Copilot Test Generation Prompt',
    tool: 'GitHub Copilot',
    assetType: 'Skills',
    category: 'Testing',
    categoryKey: 'testing',
    framework: 'Generic',
    description: 'A GitHub Copilot prompt for generating practical tests around risky code.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['GitHub Copilot', 'Testing', 'Unit Tests', 'Regression Tests', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Unit test generation', 'Regression prevention', 'Risk-based testing'],
    relatedItems: ['generate-unit-tests-skill', 'add-tests-for-risky-code-hook'],
    content: 'Generate practical tests for this code. Focus on critical behavior, edge cases, invalid inputs, and regression risks. Keep tests readable and avoid unnecessary mocking.'
  },
  {
    id: 'github-copilot-issue-to-code-workflow',
    title: 'GitHub Copilot Issue-to-Code Workflow',
    tool: 'GitHub Copilot',
    assetType: 'Workflows',
    category: 'Full-Stack',
    categoryKey: 'fullstack',
    framework: 'Generic',
    description: 'A workflow prompt for turning a GitHub issue into an implementation plan.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['GitHub Copilot', 'GitHub Issues', 'Workflow', 'Implementation Plan', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: ['Issue triage', 'Implementation planning', 'Production-ready changes'],
    relatedItems: ['plan-before-coding-hook', 'build-production-ready-feature-hook'],
    content: 'Read the issue requirements, identify affected files, clarify assumptions, propose an implementation plan, list risks, then make the smallest production-ready change. Add or update tests where appropriate.'
  },
  {
    id: 'windsurf-cascade-debugging-skill',
    title: 'Windsurf Cascade Debugging Skill',
    tool: 'Windsurf',
    assetType: 'Skills',
    category: 'Debugging',
    categoryKey: 'debugging',
    framework: 'Generic',
    description: 'A Windsurf skill for using Cascade to debug issues step by step before changing code.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Windsurf', 'Cascade', 'Debugging', 'Bug Fix', 'Root Cause', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Debug broken features',
      'Investigate runtime errors',
      'Fix frontend or backend bugs',
      'Avoid random AI code changes',
      'Verify fixes safely'
    ],
    relatedItems: ['fix-bugs-step-by-step-skill', 'find-root-cause-hook'],
    content: 'Use Cascade as a debugging partner. First inspect the relevant files, summarize the expected behavior, describe the actual behavior, identify likely root causes, and propose the smallest safe fix. Do not edit unrelated files. After the fix, explain how to verify that the bug is resolved.'
  },
  {
    id: 'windsurf-frontend-ui-polish-skill',
    title: 'Windsurf Frontend UI Polish Skill',
    tool: 'Windsurf',
    assetType: 'Skills',
    category: 'Frontend',
    categoryKey: 'frontend',
    framework: 'React',
    description: 'A Windsurf skill for improving frontend UI quality, spacing, responsiveness, and component consistency.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Windsurf', 'Cascade', 'Frontend', 'React', 'UI Polish', 'SaaS UI', 'AI Coding'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: [
      'Improve SaaS UI',
      'Polish React components',
      'Fix responsive layout issues',
      'Improve visual hierarchy',
      'Make interfaces feel more production-ready'
    ],
    relatedItems: ['improve-ui-polish-skill', 'tailwind-ui'],
    content: 'Use Cascade to polish this frontend UI. Improve layout, spacing, typography, component consistency, responsive behavior, empty states, loading states, hover states, and accessibility. Preserve the existing functionality and avoid unnecessary rewrites.'
  },
  {
    id: 'windsurf-refactor-safely-skill',
    title: 'Windsurf Refactor Safely Skill',
    tool: 'Windsurf',
    assetType: 'Skills',
    category: 'Refactoring',
    categoryKey: 'refactoring',
    framework: 'Generic',
    description: 'A Windsurf skill for safely refactoring existing code without changing behavior.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Windsurf', 'Cascade', 'Refactoring', 'Clean Code', 'Maintainability', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Refactor legacy code',
      'Improve maintainability',
      'Clean duplicated logic',
      'Simplify components',
      'Preserve existing behavior'
    ],
    relatedItems: ['refactor-legacy-code-skill', 'refactor-without-breaking-hook'],
    content: 'Use Cascade to refactor this code safely. First identify duplicated logic, unclear responsibilities, risky dependencies, and files that should not be changed. Then refactor in small steps while preserving behavior. Explain what changed and how to test it.'
  },
  {
    id: 'codex-project-planning-prompt',
    title: 'Codex Project Planning Prompt',
    tool: 'Codex',
    assetType: 'Hooks',
    category: 'Full-Stack',
    categoryKey: 'fullstack',
    framework: 'Generic',
    description: 'A Codex hook for planning implementation before writing code.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Codex', 'Planning', 'Full-Stack', 'AI Coding', 'Implementation Plan'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: [
      'Start a new feature',
      'Understand a project before editing',
      'Reduce unnecessary code changes',
      'Plan safer implementation steps',
      'Improve AI coding reliability'
    ],
    relatedItems: ['plan-before-coding-hook', 'senior-fullstack-developer-role'],
    content: 'Before writing code, inspect the project structure, identify the relevant files, clarify assumptions, list risks, and create a step-by-step implementation plan. Only start coding after the plan is clear.'
  },
  {
    id: 'codex-test-generation-skill',
    title: 'Codex Test Generation Skill',
    tool: 'Codex',
    assetType: 'Skills',
    category: 'Testing',
    categoryKey: 'testing',
    framework: 'Generic',
    description: 'A Codex skill for generating practical tests around important or risky code.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Codex', 'Testing', 'Unit Tests', 'Regression Tests', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Add unit tests',
      'Add regression tests',
      'Test risky logic',
      'Improve code confidence',
      'Prepare code for refactoring'
    ],
    relatedItems: ['generate-unit-tests-skill', 'add-tests-for-risky-code-hook'],
    content: 'Generate practical tests for this code. Focus on core behavior, edge cases, invalid inputs, regression risks, and important user flows. Keep the tests readable. Avoid excessive mocking unless necessary. Explain how to run the tests.'
  },
  {
    id: 'codex-code-review-role',
    title: 'Codex Code Review Role',
    tool: 'Codex',
    assetType: 'Roles',
    category: 'Testing',
    categoryKey: 'testing',
    framework: 'Generic',
    description: 'A Codex role for reviewing code quality, correctness, maintainability, and risk.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Codex', 'Code Review', 'Testing', 'Maintainability', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Review changed files',
      'Check risky implementation',
      'Prepare for pull request',
      'Improve maintainability',
      'Find bugs before deployment'
    ],
    relatedItems: ['ai-code-reviewer-role', 'review-pull-request-skill'],
    content: 'Act as a senior code reviewer. Review this code for correctness, edge cases, security risks, performance issues, readability, duplicated logic, maintainability, and missing tests. Prioritize the most important findings first and suggest concrete improvements.'
  },
  {
    id: 'codex-documentation-skill',
    title: 'Codex Documentation Skill',
    tool: 'Codex',
    assetType: 'Skills',
    category: 'Documentation',
    categoryKey: 'documentation',
    framework: 'Generic',
    description: 'A Codex skill for creating useful developer documentation.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Codex', 'Documentation', 'README', 'Developer Docs', 'AI Coding'],
    difficulty: 'Beginner',
    popularity: 'medium',
    useCases: [
      'Generate README',
      'Document setup steps',
      'Explain project structure',
      'Help new developers onboard',
      'Improve open-source presentation'
    ],
    relatedItems: ['write-readme-docs-skill', 'explain-codebase-hook'],
    content: 'Create or improve the documentation for this project. Include project purpose, tech stack, setup steps, environment variables, scripts, folder structure, deployment notes, common troubleshooting tips, and examples where helpful.'
  },
  {
    id: 'codex-deployment-readiness-workflow',
    title: 'Codex Deployment Readiness Workflow',
    tool: 'Codex',
    assetType: 'Workflows',
    category: 'DevOps',
    categoryKey: 'devops',
    framework: 'Generic',
    description: 'A Codex workflow for checking whether a project is ready to build and deploy.',
    source: { label: 'AI Agent Dock' },
    license: 'MIT',
    tags: ['Codex', 'Deployment', 'DevOps', 'Build', 'Cloudflare Pages', 'AI Coding'],
    difficulty: 'Intermediate',
    popularity: 'medium',
    useCases: [
      'Prepare for Cloudflare Pages',
      'Prepare for Vercel',
      'Check build errors',
      'Review environment variables',
      'Avoid deployment failures'
    ],
    relatedItems: ['prepare-for-deployment-hook', 'devops-deployment-expert-role'],
    content: 'Check this project for deployment readiness. Review build scripts, environment variables, static assets, routes, dependency issues, framework configuration, output directory, and deployment target. List anything likely to fail during build or deployment, then suggest fixes.'
  }
];
